version: "3.1"

services:
  docker-registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /mnt/registry/auth/registry.password
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /mnt/registry/data
    volumes:
      - /Users/user/mnt/registry/data:/mnt/registry/data
      - /Users/user/mnt/registry/auth/registry.password:/mnt/registry/auth/registry.password
  pgdatabase:
    image: postgres:10.4
    container_name: pgdatabase
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: man
      POSTGRES_DB: appear
      PGDATA: /mnt/database
    volumes:
      - /Users/user/mnt/database:/mnt/database
    ports:
      - "5432:5432"